-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 16:31:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Student_Aid_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Student_Aid_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Student_Aid_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Student_Aid_DB` ;

-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`CampusBasedVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`CampusBasedVolume` (
  `OPE ID` INT(8) NOT NULL,
  `SchoolName` VARCHAR(125) NULL,
  `State` VARCHAR(2) NULL,
  `ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  `SchoolType` VARCHAR(20) NOT NULL,
  `Recipients` INT(8) NULL DEFAULT NULL,
  `Disbursemenets` VARCHAR(20) NULL DEFAULT NULL,
  `FSEOGFederalAward` VARCHAR(20) NULL DEFAULT NULL,
  `FSEOGDisbursements` VARCHAR(20) NULL DEFAULT NULL,
  `FSWFederalAward` VARCHAR(20) NULL DEFAULT NULL,
  `FSWDisbursements` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`SchoolType`, `OPE ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`DirectLoanDisbursements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`DirectLoanDisbursements` (
  `CIPcode` DECIMAL(10,0) NOT NULL,
  `ProgramTitle` VARCHAR(72) NULL DEFAULT NULL,
  `Recipients` VARCHAR(6) NULL DEFAULT NULL,
  `Disbursements` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`CIPcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`FFELVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`FFELVolume` (
  `OPE ID` INT(8) NOT NULL,
  `SchoolName` VARCHAR(125) NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  `SchoolType` VARCHAR(20) NOT NULL,
  `Recipients` INT(8) NULL DEFAULT NULL,
  `NumOfLoansOriginated` INT(8) NULL DEFAULT NULL,
  `DollarOfLoansOriginated` VARCHAR(20) NULL DEFAULT NULL,
  `NumOfDisbursements` INT(8) NULL DEFAULT NULL,
  `DollarOfDisbursements` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`SchoolType`, `OPE ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`GainfulEmployment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`GainfulEmployment` (
  `OPE ID` INT(8) NOT NULL,
  `SchoolName` VARCHAR(125) NULL,
  `StreetAddress` VARCHAR(72) NULL DEFAULT NULL,
  `City` VARCHAR(32) NULL DEFAULT NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `Zip` VARCHAR(10) NULL DEFAULT NULL,
  `SchoolType` VARCHAR(25) NULL,
  `CIPCode` INT(6) NOT NULL,
  `CIPName` VARCHAR(70) NOT NULL,
  `CredentialLevel` VARCHAR(45) NULL DEFAULT NULL,
  `RepaymentRate` DECIMAL(10,0) NULL DEFAULT NULL,
  `RepaymentRateNumerator` VARCHAR(12) NULL DEFAULT NULL,
  `RepaymentRateDenominator` VARCHAR(12) NULL DEFAULT NULL,
  `DebtToEarningsAnnualRate` DECIMAL(10,0) NULL DEFAULT NULL,
  `DebtToEarningsAnnualRateNumerator` VARCHAR(12) NULL DEFAULT NULL,
  `DebtToEarningsAnnualRateDenominator` VARCHAR(12) NULL DEFAULT NULL,
  `DebtToEarningsDicretionaryRate` DECIMAL(10,0) NULL DEFAULT NULL,
  `DebtToEarningsDicretionaryRateNumerator` VARCHAR(12) NULL DEFAULT NULL,
  `DebtToEarningsDicretionaryRateDenominator` VARCHAR(12) NULL DEFAULT NULL,
  `MedianPrivateLoans` VARCHAR(12) NULL DEFAULT NULL,
  `MedianInstitutionLoans` VARCHAR(12) NULL DEFAULT NULL,
  `MedianTitleIVLoans` VARCHAR(12) NULL DEFAULT NULL,
  `MedianTitleIVLoans(2010-2011AwardYear)` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`OPE ID`, `CIPCode`, `CIPName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`GrantVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`GrantVolume` (
  `OPE ID` INT(8) NULL,
  `SchoolName` VARCHAR(125) NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  `SchoolType` VARCHAR(20) NULL,
  `YTDRecipients` INT(8) NULL DEFAULT NULL,
  `YTDDisbursements` VARCHAR(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`LoanVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`LoanVolume` (
  `OPE ID` INT(8) NOT NULL,
  `SchoolName` VARCHAR(125) NULL,
  `State` VARCHAR(2) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  `SchoolType` VARCHAR(20) NULL,
  `Recipients` INT(8) NULL DEFAULT NULL,
  `NumOfLoansOriginated` INT(8) NULL DEFAULT NULL,
  `DollarOfLoansOriginated` VARCHAR(20) NULL DEFAULT NULL,
  `NumOfDisbursements` INT(8) NULL DEFAULT NULL,
  `DollarOfDisbursements` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`OPE ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`School` (
  `SchoolCode` VARCHAR(6) NOT NULL,
  `SchoolName` VARCHAR(200) NULL,
  `SchoolAddress` VARCHAR(72) NULL DEFAULT NULL,
  `City` VARCHAR(32) NULL DEFAULT NULL,
  `StateCode` VARCHAR(2) NULL DEFAULT NULL,
  `ZipCode` VARCHAR(5) NULL DEFAULT NULL,
  `Province` VARCHAR(20) NULL DEFAULT NULL,
  `Country` VARCHAR(12) NULL DEFAULT NULL,
  `PostalCode` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`SchoolCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`CampusBasedVolume_has_GrantVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`CampusBasedVolume_has_GrantVolume` (
  `CampusBasedVolume_OPE ID` INT(8) NOT NULL,
  `CampusBasedVolume_SchoolName` VARCHAR(125) NOT NULL,
  `CampusBasedVolume_SchoolType` VARCHAR(20) NOT NULL,
  `GrantVolume_SchoolType` VARCHAR(20) NOT NULL,
  `GrantVolume_OPE ID` INT(8) NOT NULL,
  `GrantVolume_SchoolName` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`CampusBasedVolume_OPE ID`, `CampusBasedVolume_SchoolName`, `CampusBasedVolume_SchoolType`, `GrantVolume_SchoolType`, `GrantVolume_OPE ID`, `GrantVolume_SchoolName`),
  INDEX `fk_CampusBasedVolume_has_GrantVolume_GrantVolume1_idx` (`GrantVolume_SchoolType` ASC, `GrantVolume_OPE ID` ASC, `GrantVolume_SchoolName` ASC) VISIBLE,
  INDEX `fk_CampusBasedVolume_has_GrantVolume_CampusBasedVolume_idx` (`CampusBasedVolume_OPE ID` ASC, `CampusBasedVolume_SchoolName` ASC, `CampusBasedVolume_SchoolType` ASC) VISIBLE,
  CONSTRAINT `fk_CampusBasedVolume_has_GrantVolume_CampusBasedVolume`
    FOREIGN KEY (`CampusBasedVolume_OPE ID` , `CampusBasedVolume_SchoolName` , `CampusBasedVolume_SchoolType`)
    REFERENCES `Student_Aid_DB`.`CampusBasedVolume` (`OPE ID` , `SchoolName` , `SchoolType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CampusBasedVolume_has_GrantVolume_GrantVolume1`
    FOREIGN KEY (`GrantVolume_SchoolType` , `GrantVolume_OPE ID` , `GrantVolume_SchoolName`)
    REFERENCES `Student_Aid_DB`.`GrantVolume` (`SchoolType` , `OPE ID` , `SchoolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`School_has_School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`School_has_School` (
  `School_SchoolCode` VARCHAR(6) NOT NULL,
  `School_SchoolName` VARCHAR(200) NOT NULL,
  `School_SchoolCode1` VARCHAR(6) NOT NULL,
  `School_SchoolName1` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`School_SchoolCode`, `School_SchoolName`, `School_SchoolCode1`, `School_SchoolName1`),
  INDEX `fk_School_has_School_School2_idx` (`School_SchoolCode1` ASC, `School_SchoolName1` ASC) VISIBLE,
  INDEX `fk_School_has_School_School1_idx` (`School_SchoolCode` ASC, `School_SchoolName` ASC) VISIBLE,
  CONSTRAINT `fk_School_has_School_School1`
    FOREIGN KEY (`School_SchoolCode` , `School_SchoolName`)
    REFERENCES `Student_Aid_DB`.`School` (`SchoolCode` , `SchoolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_School_has_School_School2`
    FOREIGN KEY (`School_SchoolCode1` , `School_SchoolName1`)
    REFERENCES `Student_Aid_DB`.`School` (`SchoolCode` , `SchoolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Student_Aid_DB`.`School_has_LoanVolume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Student_Aid_DB`.`School_has_LoanVolume` (
  `School_SchoolCode` VARCHAR(6) NOT NULL,
  `School_SchoolName` VARCHAR(200) NOT NULL,
  `LoanVolume_OPE ID` INT(8) NOT NULL,
  `LoanVolume_SchoolName` VARCHAR(125) NOT NULL,
  `LoanVolume_SchoolType` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`School_SchoolCode`, `School_SchoolName`, `LoanVolume_OPE ID`, `LoanVolume_SchoolName`, `LoanVolume_SchoolType`),
  INDEX `fk_School_has_LoanVolume_LoanVolume1_idx` (`LoanVolume_OPE ID` ASC, `LoanVolume_SchoolName` ASC, `LoanVolume_SchoolType` ASC) VISIBLE,
  INDEX `fk_School_has_LoanVolume_School1_idx` (`School_SchoolCode` ASC, `School_SchoolName` ASC) VISIBLE,
  CONSTRAINT `fk_School_has_LoanVolume_School1`
    FOREIGN KEY (`School_SchoolCode` , `School_SchoolName`)
    REFERENCES `Student_Aid_DB`.`School` (`SchoolCode` , `SchoolName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_School_has_LoanVolume_LoanVolume1`
    FOREIGN KEY (`LoanVolume_OPE ID` , `LoanVolume_SchoolName` , `LoanVolume_SchoolType`)
    REFERENCES `Student_Aid_DB`.`LoanVolume` (`OPE ID` , `SchoolName` , `SchoolType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
